server {
    listen 80;
    server_name scholarhub.yendev.pro;

    root /usr/share/nginx/html;
    index index.html;

    # Cấu hình "bất tử" cho React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Tùy chọn: Cache các file tĩnh (ảnh, css, js) để web load siêu nhanh
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|mp4)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}